# Generated by Django 4.2.5 on 2023-09-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContinentConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('world', models.FloatField()),
                ('oecd', models.FloatField()),
                ('brics', models.FloatField()),
                ('europe', models.FloatField()),
                ('north_america', models.FloatField()),
                ('latin_america', models.FloatField()),
                ('asia', models.FloatField()),
                ('pacific', models.FloatField()),
                ('africa', models.FloatField()),
                ('middle_east', models.FloatField()),
                ('cis', models.FloatField()),
            ],
        ),
    ]
