# Generated by Django 4.2.5 on 2023-09-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('china', models.IntegerField()),
                ('usa', models.IntegerField()),
                ('belgium', models.IntegerField()),
                ('croatia', models.IntegerField()),
                ('france', models.IntegerField()),
                ('germany', models.IntegerField()),
                ('italy', models.IntegerField()),
                ('netherlands', models.IntegerField()),
                ('poland', models.IntegerField()),
                ('portugal', models.IntegerField()),
                ('romania', models.IntegerField()),
                ('spain', models.IntegerField()),
                ('sweden', models.IntegerField()),
                ('uk', models.IntegerField()),
                ('norway', models.IntegerField()),
                ('turkey', models.IntegerField()),
                ('kazakhstan', models.IntegerField()),
                ('russia', models.IntegerField()),
                ('ukraine', models.IntegerField()),
                ('uzbeckistan', models.IntegerField()),
                ('argentina', models.IntegerField()),
                ('canada', models.IntegerField()),
                ('chile', models.IntegerField()),
                ('colubia', models.IntegerField()),
                ('mexico', models.IntegerField()),
                ('venezuela', models.IntegerField()),
                ('indonesia', models.IntegerField()),
                ('japan', models.IntegerField()),
                ('malaysia', models.IntegerField()),
                ('south_korea', models.IntegerField()),
                ('taiwan', models.IntegerField()),
                ('thailand', models.IntegerField()),
                ('india', models.IntegerField()),
                ('australia', models.IntegerField()),
                ('new_zealand', models.IntegerField()),
                ('algeria', models.IntegerField()),
                ('egypt', models.IntegerField()),
                ('nigeria', models.IntegerField()),
                ('south_africa', models.IntegerField()),
                ('kuwait', models.IntegerField()),
                ('saudi_arabia', models.IntegerField()),
                ('u_a_e', models.IntegerField()),
            ],
        ),
    ]
