# Generated by Django 4.2.5 on 2023-09-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data', '0003_alter_countryconsumption_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryconsumption',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
