# Generated by Django 4.2.5 on 2023-09-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data', '0004_alter_countryconsumption_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonRenewablesTotalPowerGenerated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_generation', models.CharField(max_length=100)),
                ('contribution_twh', models.FloatField()),
            ],
        ),
    ]
