# Generated by Django 4.2.5 on 2023-09-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('display_data', '0005_nonrenewablestotalpowergenerated'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenewablesPowerGenerated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('hydro', models.FloatField()),
                ('biofuels', models.FloatField()),
                ('solar', models.FloatField()),
                ('geo_thermal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RenewableTotalPowerGenerated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('mode_of_generation', models.CharField(max_length=100)),
                ('contribution_twh', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TopTwentyRenewableCountries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('hydro', models.FloatField()),
                ('biofuels', models.FloatField()),
                ('solar', models.FloatField()),
                ('geo_thermal', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
    ]
