# Generated by Django 4.2.5 on 2023-09-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data', '0006_renewablespowergenerated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryconsumption',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
