# Generated by Django 4.2.5 on 2023-10-04 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display_data', '0008_alter_countryconsumption_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countryconsumption',
            old_name='croatia',
            new_name='czechia',
        ),
    ]
