# Generated by Django 4.2.5 on 2023-10-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data', '0009_rename_croatia_countryconsumption_czechia'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryconsumption',
            name='brazil',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
