# Generated by Django 4.2.5 on 2023-10-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data', '0010_countryconsumption_brazil'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryconsumption',
            name='iran',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
