# Generated by Django 4.2.5 on 2023-10-05 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data', '0011_countryconsumption_iran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renewablepowergenerated',
            name='year',
            field=models.IntegerField(unique=True),
        ),
    ]
